import './webform-editor.css'
import './createForm.html'
import './updateForm.html'
import './createFormAfter.html'
import './updateFormAfter.html'
import './detailsView.html'
import './help.html'

import './service'
import './events'
