import './detailsView.html'
import './createFormPre.html'
import './updateFormPre.html'
import './createFormPre.html'
import './servicesAgentCommonConfig'
import './help'

import './service'
import './events'
import './helpers'
import './index.css'