import './detailsView.html'
import './createFormPre.html'
import './updateFormPre.html'
import './createFormPre.html'
import './servicesAgentExecuteConfig'
import './servicesAgentNodejsConfig'

import './service'
import './helpers'
import './index.css'